project_biu.configs.agents.PlusAgent
A,B
C
project_biu.configs.agents.MulAgent
A,C
D
project_biu.configs.agents.IncAgent
D
E
project_biu.configs.agents.MovingAverageAgent
E
F
project_biu.configs.agents.MaxTrackerAgent
F
G
project_biu.configs.agents.CounterAgent
G
H
project_biu.configs.agents.CounterAgent
H
G